### ISSUE TITLE
Instructions on how to ConVars and Commands are dumped and converted to JSON

### ISSUE THREAD

**Issue by femboyfin** [Poggicek/cs2-docs#5]
I've looked through the [docs](https://cs2.poggu.me/reverse-engineering/ConVars) briefly and wasn't able to spot any instructions or information on how the data included in the [Commands](https://cs2.poggu.me/dumped-data/command-list) nor [ConVars](https://cs2.poggu.me/dumped-data/convar-list) sections of the dumped-data portion of the site are gathered. I'm assuming it's a partially manual, partially automated process (at least for converting the files to the JSON schema used [here](https://github.com/Poggicek/cs2-docs/blob/master/src/components/CommandList/commands.json)). I'd like to contribute updates to the table myself when new versions are released, but I'm not sure how.

**Comment by Poggicek** [comment]
It's a custom dll that upon injection dumsp all the convars and commands and stores them in a json file
